### ISSUE TITLE
MOPPeR assumes its running inside its source tree

### ISSUE THREAD

**Issue by dsroberts** [ACCESS-Community-Hub/ACCESS-MOPPeR#107]
There seems to be a few places in the code where MOPPeR is assuming its running inside its own source tree (e.g. https://github.com/ACCESS-Community-Hub/ACCESS-MOPPeR/blob/d5ca362a988020a96e4057bade882a7b81b888c3/mopper/setup_utils.py#L563

Best to use something like this: https://stackoverflow.com/questions/10174211/how-to-make-an-always-relative-to-current-module-file-path to ensure MOPPeR can be run out of any working directory.

**Comment by paolap** [comment]
Thanks it's good to have an issue to remind myself about this. It's something we need to work out yet, as there's a lot of input files that are needed and can be distributed with the repo, so it's not ideal for the moment was the easiest thing to do, once we have a sense of all the files that needs to be used it will be easier to work out a proper workflow. Especially for the db I spotted once a way to have a db repo, which would be ideal however at the moment that's free but it might not staying free in the future.

**Comment by paolap** [comment]
I think to progress with this, we need different strategies depending on the type of file: 

1) Files that come as part of the compiled package as some yaml files defining dictionaries used by the code. These are user independent and can be accessed using pkg_resources:
 fname = pkg_resources.resource_filename(__name__, 'data/<filename>')

2) Files which are fully handled by the user like specific mappings etc and these use (already) a full path which is created based on the configuration file


3) Files which are distributed with the package but can be potentially augmented (CMOR tables) and/or substituted (database). For these we need an approach that will work either way. We could start with adding these to the package data but give the user an option to provide their own version via the configuration file. In that case we'll need to access their filenames as in point one only if the user hasn't explicitly overrun the default option in the configuration file. 

As usually the path passed to the configuration files point to folders with lots of files,  it would be good to implement this in a way in which you can pass a folder that only contains the files you modified/added. Then the tool could fall back on package data for any files it can't find there.

**Comment by paolap** [comment]
turns out this:

fname = pkg_resources.resource_filename(__name__, 'data/<filename>')
is obsolete so instead using 
import_resources.files()

I also updated the overall structure to make it easier to distinguish what's in the package. Haven't tested yet if this works

**Comment by paolap** [comment]
This is now done, I tested both mopdb and mop commands and they work. However, it might be that a slightly different workflow using a file I haven't yet try to open might fail.
