### ISSUE TITLE
Rechunk variables along model levels if necessary for interpolation onto pressure levels.

### ISSUE THREAD

**Issue by dsroberts** [ACCESS-Community-Hub/ACCESS-MOPPeR#114]
Just got this when attempting to create pressure level files
```
E: Unable to extract var because: dimension model_theta_level_number 
on 0th function argument to apply_ufunc with dask='parallelized' consists of multiple chunks, 
but is also a core dimension. To fix, either rechunk into a single array chunk along this dimension, 
i.e., ``.chunk(dict(model_theta_level_number=-1))``, or pass ``allow_rechunk=True`` in 
``dask_gufunc_kwargs`` but beware that this may significantly increase memory usage.
```
Guess we should rechunk along whatever vertical coordinate the model uses. I assume this is a no-op if the chunking is already correct?

**Comment by paolap** [comment]
I think we fixed this already, in fact I have no issue creating variables with the latest version just today and 24.01 env. I remember this popped up for me before (hence I think it was fixed) but after we worked on AUS2200. However, I'm testing this on a different experiment so I will try with the latest data after I fixed the other issues

**Comment by paolap** [comment]
ok I quickly verified that we already do this in latest version:

 var = var.chunk({lev: -1})
 pmod = pmod.chunk({lev: -1})
